sudo: true
dist: trusty

env:
  global:
    - REPO="${DOCKER_USER}/docker-php-nginx"
    - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: build and test docker image
      script:
      - docker build -t $REPO:$COMMIT .
      - docker images
      - docker run --rm $REPO:$COMMIT cat /www/index.html
    - stage: push
      script:
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - docker push $REPO
